### ISSUE TITLE
Don't work after update Atom-Linter.

### ISSUE THREAD

**Issue by pyvim** [AtomLinter/linter-flake8#60]
Hello. I have problem with work (don't work) linter-flake8 after update atom-linter to version 1.3.0.

**Comment by thedandroid** [comment]
+1

**Comment by Arcanemagus** [comment]
This will be fixed as soon as @badray reviews/merges in https://github.com/AtomLinter/linter-flake8/pull/56.

**Comment by pyvim** [comment]
I hope that soon. Now I work with [pylama](https://github.com/AtomLinter/linter-pylama).

**Comment by badray** [comment]
Fixed in #56

**Comment by thedandroid** [comment]
This is still not fixed. I have removed and reinstalled both linter and linter-flake8 to my regular workspace, laptop and virtual machines. Linter shows no feedback. 0 errors no matter the context.

**Comment by Arcanemagus** [comment]
@thedandroid Are other linters working properly?

**Comment by thedandroid** [comment]
Yes, I switched to linter-pylama in the mean time and it works fine.

**Comment by Arcanemagus** [comment]
Does flake8 work from your command line interface?

**Comment by thedandroid** [comment]
Yes:
`dandroid@saidin ~> flake8 --version
2.4.1 (pep8: 1.5.7, mccabe: 0.3.1, pyflakes: 0.8.1) CPython 2.7.9 on Linux`

**Comment by Arcanemagus** [comment]
If you open Atom's dev tools and put a breakpoint on line 66 of `main.coffee` are you getting any text in the `result` variable?

**Comment by thedandroid** [comment]
I'm not familiar with the Atom debugger, but when I put a breakpoint at line 66 of `~/.atom/packages/linter-flake8/lib/main.coffee` it never reaches the breakpoint to check the variable.

I experimented with putting breakpoints in the linter-pylama package, just to check myself, and the debugger hits and breaks. Am I doing something incorrectly?

**Comment by Arcanemagus** [comment]
Hmm, looks like it's showing the compiled code in there, it's actually line 76:
![result](https://cloud.githubusercontent.com/assets/427137/9049989/7c09962a-39fd-11e5-838e-becbf6be3fc3.png)

You might also try setting the "Executable Dir" setting to the folder where flake8 is located. There have been some issues with environment variables not being passed around correctly leading to the linter executables not being ran.

**Comment by thedandroid** [comment]
I still can't seem to get anything from it. No feedback and it never seems to reach line 76 to break. I created a brand new install with nothing but linter and linter-flake8 and get the same thing.

Not sure what's going on, but I think I'm going to move on. Thanks for the help and sorry for the bother!

**Comment by code-tree** [comment]
Just a quick note that I couldn't get this plugin to work, until I realised that although flake8 was ok, pep8 had a bug that was failing for some file inputs, which was fixed for me by upgrading to pep8 1.6.2

@thedandroid: I've noticed you are running pep8 1.5.7 (not sure if this will help you or not though)

**Comment by tvavrys** [comment]
Everything worked fine until I updated the package to 1.6.0.

/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260 Uncaught BufferedProcessError: Failed to spawn command `flake8`. Make sure `flake8` is installed and on your PATH

**Comment by badray** [comment]
Hold on, I see potential issue. I'll try to patch it now.

**Comment by badray** [comment]
I know what is potencial issue @tvavrys @thedandroid. @steelbrain is not using `ExecutableDir` variable, which was used in `1.5.0`, so your atom binary ask system for `flake8` which is not in `Node` path variable, `process.env` if I remember right:).

@tvavrys @thedandroid Please try to put full path in `Executable path` in `linter-flake8` settings for ex. `/usr/local/bin/flake8`. And see if it works.

![zrzut ekranu 2015-08-04 16 48 07](https://cloud.githubusercontent.com/assets/895344/9063687/0676c30c-3ac9-11e5-8183-0b31192831ed.png)

I'll fix it after I'll return from my work - Warsaw is littlebit gridlocked, so expect patch in 3/4 hours.

Sorry for such buggy release - I was releasing it with hurry becouse plugin wasnt working with new AtomLinter version - I slept over the best moment to do it becouse i was on holidays.

**Comment by tvavrys** [comment]
@badray It fixed the problem.

**Comment by badray** [comment]
@tvavrys :+1: Sorry again for your inconvenience.

**Comment by tvavrys** [comment]
@badray No problem at all. Thanks for fixing it.

**Comment by badray** [comment]
Yesterday I was confused little bit how to fix it, so i didn't done it. But I have one idea - how about to remove `Executable Dir` and left only `Executable Path` variable?

**Comment by uellner** [comment]
it looks good for me!

**Comment by Arcanemagus** [comment]
@badray just a note: All of the other linters I've seen/worked on only have Executable Path :wink:.

**Comment by JazzJay** [comment]
Just find the path that has flake8
exam: my flake8 in /Library/Frameworks/Python.framework/Versions/3.4/bin/flake8
so I change Executable Path :  /Library/Frameworks/Python.framework/Versions/3.4/bin/flake8
That problem is gone.

**Comment by thinkpointclick** [comment]
If you are on a Mac. Start Terminal and run `mdfind flake8`

Select and copy /bin/flake8 path
![image](https://cloud.githubusercontent.com/assets/6320476/13935040/a6bc8b0e-ef8b-11e5-9e76-0f8743887e1a.png)

and paste it in the linter-flake8 settings
![image](https://cloud.githubusercontent.com/assets/6320476/13935063/c77387b2-ef8b-11e5-827f-78abce611733.png)

You should be good to go.
